<?php

/**
 * @file
 * Provides multiple plugins for the Restaurant Distribution
 */

/**
 * Implements hook_ctools_plugin_directory().
 */ 
function restaurant_plugins_ctools_plugin_directory($module, $plugin) {
  return 'plugins/' . $plugin;
}

/**
 * Implements hook_theme().
 */
function restaurant_plugins_theme() {
  return array(
    'contact_block' => array(
      'variables' => array('address' => NULL, 'phone' => NULL),
      'file' => 'restaurant_plugins.theme.inc',
    ),
  );
}
